networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    platform: linux/amd64
    container_name: gateway
    volumes:
      - ./backend/:/var/www/backend
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${HOST_PORT}:80"
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build:
      context: docker/php/
      args:
        UID: ${UID}
        GID: ${GID}
        UNAME: ${UNAME}
    container_name: api-server
    volumes:
      - ./backend/:/var/www/backend
      - ./docker/php/conf.d/z-xdebug.ini:/usr/local/etc/php/conf.d/z-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=${COMPOSE_PROJECT_NAME}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17.5
    platform: linux/amd64
    container_name: database
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DEV_DB_PORT}:5432"
    logging:
      driver: "json-file"
    networks:
      - app-network
